### ISSUE TITLE
tinysound port to Linux

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/tinyheaders#12]
If you enjoyed these headers please consider contributing a Linux audio port of tinysound :)

tinysound cannot run on Linux. Right now only Windows/Apple are supported through DirectSound and CoreAudio. tinysound is ready to be ported. A port would be a prime project for someone looking to contribute to open source. Here's how:

- `tsContext` holds OS-specific pointers or handles.
- `tsMakeContext` initializes `tsContext` and calls into OS-specific APIs.
- `tsShutdownContext` frees any memory allocated in `tsMakeContext`, and calls into OS-specific APIs.
- `tsMix` is platform independent, portable C code. However, it calls `tsPosition` and `tsMemcpyToDS`, both are platform specific to Windows DirectSound. These two functions will need to be deleted/rewritten using OS-specific APIs. There are also similar calls to CoreAudio specific functions.

Summary: Loading the tsContext and shutting it down requires OS-specific code. Mixing is platform independent, and is just adding floats together then converting them into 16-bit integers. However, writing these 16-bit integers to the sound API is OS-specific.

**Comment by DeXP** [comment]
How about SDL? Yep, it's too fat dependency in general case. But Steam requires SDL as a dependency in Linux. Also, SDL is the most common game-library, used in Linux. It's preinstalled on almost all Linux-machines. 
One more advantage of SDL - it supports a lot of backends: ALSA, OSS, PulseAudio etc. It will work on any Linux distro, does not depend on wich sound system was used.
As an additional profit - a lot of supported OSes, Android included.

**Comment by RandyGaul** [comment]
I would totally happy with an SDL port! This is a pretty good idea. The header itself can run natively on Windows/Apple operating systems already, so adding in the final port as SDL would be a great option. SDL port can be enabled in the header via pre processor very easily.

**Comment by RandyGaul** [comment]
Obviously, though, SDL_Mixer should have nothing to do with tinysound. I originally wrote tinysound because I hated SDL_Mixer API.

**Comment by DeXP** [comment]
Ok, I have compiled basic skeleton. Now it's only left to make music work! x-D
How does `tsMix` works? At start I ask TinySound "please, prebuf 5 seconds for me", but I call `tsMix` every 10 ms. It must mix all current sounds into one? Only current 10ms slice? Why `GetCurrentPosition` used in Windows? Do you calculate it by yourself in Mac?
P.S. I have not found any function for Yield in SDL. :-(

**Comment by RandyGaul** [comment]
Yep tsMix mixes all sounds together. Yep, tsMix keeps a latency buffer of samples. `GetCurrentPosition` gets positions of circular buffer inside of DirectSound. On Mac the circular buffer must be implemented manually.

More info:

tsMix will try to buffer the latency a head of where the underlying API reads samples. So for DirectSound, it gives you a play_cursor and write_cursor. You write samples to the write_cursor with tsMix, and tsMix will generally keep the write_cursor latency_seconds ahead of the player_cursor. DirectSound will be reading samples and playing them from the play_cursor. These cursors come from `GetCurrentPosition`.

For Mac I implemented the delay myself, but it is identical to DirectSound. Samples are written a little ahead of where CoreAudio reads. There is a buffer of latency samples between the reading and the writing. In between is a circular buffer. On Mac I had to implement the circular buffer explicitly. In DirectSound the circular buffer is mostly hidden within DirectSound.

**Comment by RandyGaul** [comment]
I looked into SDL here: https://wiki.libsdl.org/SDL_AudioSpec

This should work. SDL_AudioCallback can be setup very similarly to `tsMemcpyToCA`. It looks like this callback just requests more data as needed, and can use the circular buffer implemented for Apple.

**Comment by RandyGaul** [comment]
Oh one note. This might be easier to implement https://wiki.libsdl.org/SDL_QueueAudio. This can be called at the end of tsMix.

These are just suggestions! I haven't actually ever used the SDL API before so these might not work.

**Comment by DeXP** [comment]
Great thanks! SDL_QueueAudio helped a lot. The porting in active process now.
https://github.com/DeXP/tinyheaders/blob/master/tinysound.h
What is working:
1. Low- and High-level API
2. Threads / thread pool
3. One audio stream
What is currently not:
1. The sound output for right channel only. o_O
When it will be ready, I will prepare a pull request.

**Comment by RandyGaul** [comment]
Looks pretty good overall. I noticed a small bug here: https://github.com/DeXP/tinyheaders/blob/master/tinysound.h#L1620

To set samples_to_write it looks like SDL provides: https://wiki.libsdl.org/SDL_GetQueuedAudioSize Then it is possible to do:

    int queued_samples = SDL_GetQueuedAudioSize( ctx->dev );
    int latency_samples = ctx->latency;
    TS_ASSERT( queued_samples <= latency_samples );
    int samples_to_write = latency_samples - queued_samples;

Also I think you want AUDIO_S16SYS instead of AUDIO_S16LSB in `tsMakeContext`.

**Comment by DeXP** [comment]
Now it's much better. I still have some problems with `SDL_GetQueuedAudioSize` - it always return buffer size for small buffers. I thinked to always have exactly 2 buffers of the fixed small size. But it's glitchy too... For `latency_in_Hz = 15` I need to have 5 of them. :-(
https://github.com/DeXP/tinyheaders/blob/master/tinysound.h#L1627
I'm thinking about rewriting it to own implemented ring-buffer, as it shown [here](https://davidgow.net/handmadepenguin/ch8.html).

**Comment by RandyGaul** [comment]
`tsMemcpytoCA` is using a ring buffer implementation. I would recommend using that and using the Mac implementation as a reference.

**Comment by RandyGaul** [comment]
Hmm I looked into SDL_GetQueuedAudioSize and from the docs:

> This is the number of bytes that have been queued for playback with SDL_QueueAudio(), but have not yet been sent to the hardware. This number may shrink at any time, so this only informs of pending data.

So this can not be used to determine latency samples. That's why it always gives you tiny numbers, as it is probably very quickly pushing data to the underlying API.

Unfortunately the only solution here is to use SDL's callback SDL_AudioCallback, which will be called by SDL periodically when it needs more audio data -- this is nearly identical to the implementation for Mac in tinysound.

**Comment by DeXP** [comment]
Yep, I know already about Queue-functions. My game was already Greenlit: [Wordlase](http://steamcommunity.com/sharedfiles/filedetails/?id=861528240). So I temporary moved my forces to complete the papers. Now I can return to work on engine. 
Also, I really need API to load OGG dynamically. Not preload all file and decode it. But get only needed short data chunk. It will really reduce the memory usage...

**Comment by RandyGaul** [comment]
AFAIK stb_vorbis can do streaming of ogg files: https://nothings.org/stb_vorbis/samples/sample.c

Check out uhh the pull_data API. That is probably the easiest to use. You can hand a FILE* to stb_vorbis and it can progressively pull data out of the file. This way the entire audio does not need to sit in RAM uncompressed (which is what tinysound currently does).

I figured this is OK for tinysound since users will probably have file-loading on a separate thread, so the ~1 second of latency for decoding a vorbis stream should be acceptable. But, it would definitely be nicer to have some special API for .ogg music files to use less RAM.

**Comment by r-lyeh** [comment]
An ALSA backend would be a great addition as well
FYI, http://github.com/yui0/aplay-/blob/master/alsa.h (PD)

**Comment by RandyGaul** [comment]
@DeXP Ganna take a crack at this today and see if I can knock it out. Thanks for posting up your work so far!

**Comment by RandyGaul** [comment]
@r-lyeh  That would be really sweet. Unfortunately that is something I will not be able to do myself. Feel free to open a new issue on that topic! Maybe someone will come along and add it one day :)

**Comment by RandyGaul** [comment]
Finished! Thanks to @DeXP the port was very painless. There was one big that you seemed to be struggling with. In the initialization `wanted.samples` should be a low value, since that's the internal buffer size, and will dictate how often SDL asks for samples. I set it to 1024 since that seemed to be the lowest it could go without any audio glitches. This should be good enough for people running at 30 fps as well -- but I haven't tested it yet!

Cheers!
