### ISSUE TITLE
Ray to Poly collision broken

### ISSUE THREAD

**Issue by Plastburk** [RandyGaul/tinyheaders#15]
c2RaytoPoly collision seems to be broken if the polygon is perpendicular towards the ray. As demonstrated in below gif:

![brokenraygif](https://cloud.githubusercontent.com/assets/9084859/23613090/4363befe-027e-11e7-8228-2b89437b686e.gif)

(the green lines are rays currently not colliding with anything, black lines are rays colliding with the box)

**Comment by RandyGaul** [comment]
In the meantime can you please share the inputs to the c2RayToPoly function? The positions of all verts, the ray, etc during a buggy case? That way I can make sure to fix your bug and test it out.

**Comment by Plastburk** [comment]
Absolutely!
Here is the polygon and two buggy test cases (both using the same polygon):
Poly:
```
count = 4
verts = {(0.875, -11.5), (0.875, 11.5), (-0.875, 11.5), (-0.875, -11.5)}
norms = {(1, 0), (0, 1), (-1, 0), (0, -1)}
```

Ray:
```
p = (-3.869416, 13.0693407)
d = (1, 0)
t = 4
```
	
Ray2:
```
p = (-3.869416, 13.0693407)
d = (0, -1)
t = 4
```

**Comment by RandyGaul** [comment]
Great, and you didn't use a `c2x` transform?

**Comment by RandyGaul** [comment]
Should  be good to do. Was a typo where I accidentally had `num` and `den` mixed up in an if statement. Hard to catch bug!
