### ISSUE TITLE
Macro C2_PLANE_AT error

### ISSUE THREAD

**Issue by felipefs** [RandyGaul/tinyheaders#20]
The macro C2_PLANE_AT, defined at https://github.com/RandyGaul/tinyheaders/blob/ff76ac374a6bec431d8748a82f91ec44f2952d96/tinyc2.h#L1357 raises the following error on GCC 6.3.1, Linux:

```c
tinyc2.h: In function ‘c2AntinormalFace’:
tinyc2.h:1357:29: error: expected expression before ‘{’ token
 #define C2_PLANE_AT( p, i ) { (p)->norms[ i ], c2Dot( (p)->norms[ i ], (p)->verts[ i ] ) }
                             ^
```
I think that multi-statement macros aren't ANSI/ISO C/C++, that's why it works on Visual Studio, but not on GCC. Since the macro is used in many places, the only solution I can think of is to replace it with a function or replace where the macro is used with the explicit code.

**Comment by felipefs** [comment]
I checked the lines where C2_PLANE_AT is used and I found that you are using the macro to initialize structures (c2h). So, I think that just replacing:

```c
#define C2_PLANE_AT( p, i ) { (p)->norms[ i ], c2Dot( (p)->norms[ i ], (p)->verts[ i ] ) }
```
with:
```c
#define C2_PLANE_AT( p, i ) (c2h){ p->norms[ i ], c2Dot( p->norms[ i ], p->verts[ i ] ) }
```
Seems to solve the problem. Apparently, GCC needs to know that the braces "{}" represent a c2h structure.

**Comment by mmozeiko** [comment]
It works with MSVC because it enables C++1x by default. With GCC it works if you use C++11 (or newer) - `-std=c++11`

**Comment by felipefs** [comment]
Probably works only with C++, then. I'm using C. I tried with both ```-std=c99``` and ```-std=c11```, but it didn't work. I found earlier that it would work with extensions, but that would not be ANSI/ISO and extensions aren't that widely used.

Platform: Linux
Compiler: GCC 6.3.1

**Comment by mmozeiko** [comment]
Yes, with C this won't work unless it is used directly in initializer:

    c2h t = C2_PLANE_AT(...);

This is not different from MSVC. It works there exactly the same as in GCC.

**Comment by felipefs** [comment]
Yes, there's one case in particular that the macro isn't used for initialization:

```c
c2h h = c2Mulxh( x, C2_PLANE_AT( p, i ) );
```

That's why adding the ```(c2h)``` fixed. The other cases are ok (all using for initialization).

**Comment by mmozeiko** [comment]
What I wanted to tell that just adding (c2h) is a wrong fix. It won't work, for example, for MSVC when compiling as C++ code: https://godbolt.org/g/VdV9Ek

Proper way is to create a new temporary local variable or change C2_PLANE_AT to a function.

**Comment by felipefs** [comment]
Agreed. Changing C2_PLANE_AT to a function seems to be more reasonable to guarantee the library is cross-platform.

**Comment by RandyGaul** [comment]
Good change, thanks! I'll add you both as contributors.
