### ISSUE TITLE
Compiling tinyc2 on Mac OSX

### ISSUE THREAD

**Issue by Smilex** [RandyGaul/tinyheaders#26]
Hey.

I used tinyc2 for a gamejam project and had same issues compiling it on my friend's Apple laptop.
I don't know anything about versions of his stuff.

I'll post a diff here if you are at all interested in this. The changes were minimal.
I'm sorry that line numbers aren't included, also I don't have the energy or time to make a proper diff or Github pull request.

```
diff linux_gamejam_2017_kopi/tinyc2.h linux_gamejam_2017_original/tinyc2.h
1357c1357
< #define C2_PLANE_AT( p, i ) (c2h){ (p)->norms[ i ], c2Dot( (p)->norms[ i ], (p)->verts[ i ] ) }
---
> #define C2_PLANE_AT( p, i ) { (p)->norms[ i ], c2Dot( (p)->norms[ i ], (p)->verts[ i ] ) }
1422c1422
< 	if ( h ) *h = (c2h){ c2CCW90( in ), c2Dot( c2CCW90( in ), ra ) };
---
> 	if ( h ) *h = { c2CCW90( in ), c2Dot( c2CCW90( in ), ra ) };
```

**Comment by RandyGaul** [comment]
Thanks for posting this. All good, I know exactly where this code is! Mind if I check out your gamejam project? :)

**Comment by Smilex** [comment]
https://itch.io/jam/linux-jam-2017/rate/128805

I was way over ambitious on this one, and it never truly became a game. But I also didn't have any good idea for a game at the time.
Most of the work went towards creating some game editor tools

**Comment by RandyGaul** [comment]
Closing this for now. I've swapped back and forth a couple times on that line of code. For now it's sitting as a normal function to ensure it compiles on different compilers.
