### ISSUE TITLE
How to properly create a c2Poly?

### ISSUE THREAD

**Issue by felipefs** [RandyGaul/tinyheaders#27]
When creating a `c2Poly` structure, should I set the values of `norms` myself? And if so, what's the proper way?

**Comment by RandyGaul** [comment]
From header docs

    // runs c2Hull and c2Norms, assumes p->verts and p->count are both set to valid values
    void c2MakePoly( c2Poly* p );

So we look over at c2MakePoly source

    void c2MakePoly( c2Poly* p )
    {
        p->count = c2Hull( p->verts, p->count );
        c2Norms( p->verts, p->norms, p->count );
    }

Up a couple lines

    norms[ i ] = c2Norm( c2CCW90( e ) );

Looks like all of the values of c2Poly are set by c2MakePoly. Here's some snippets from examples file

https://github.com/RandyGaul/tinyheaders/blob/master/examples_tinygl_and_tinyc2/main.cpp#L592
https://github.com/RandyGaul/tinyheaders/blob/master/examples_tinygl_and_tinyc2/main.cpp#L773-L793
https://github.com/RandyGaul/tinyheaders/blob/master/examples_tinygl_and_tinyc2/main.cpp#L836

An example of manually constructing some AABB polys
https://github.com/RandyGaul/tinyheaders/blob/master/examples_tinygl_and_tinyc2/main.cpp#L797-L816

**Comment by felipefs** [comment]
Thanks for the detailed info!
