### ISSUE TITLE
Time library error

### ISSUE THREAD

**Issue by star-tek-mb** [RandyGaul/tinyheaders#28]
I have checked your tinytime.h library and found one error. This error is in linux realization. Sometimes, returned delta time is less than 0. It happens every second. And i think error is in nanoseconds only. There should be also seconds. Sorry for my english. Just look to code, it can look like this:

~~~c
float delta = (float) (double)(end.tv_sec - start.tv_sec) + ((double)(end.tv_nsec - start.tv_nsec) * 1.0e-9);
~~~

**Comment by RandyGaul** [comment]
The return value from ttTime is sometimes negative? That makes sense. I have never tested the Linux version myself yet. `now.tv_sev` and `prev.tv_sev` are not used, so there may be a bug in here.

Can you submit a pull request with a fix?

**Comment by star-tek-mb** [comment]
I have submitted pull request #29.

**Comment by RandyGaul** [comment]
Thank you very much! Looks good :)
