### ISSUE TITLE
c2RaytoAABB missing check if cast.t < 0

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#31]
I just did some more testing and found out that if the `c2AABB` is over `ray.p` then `c2Raycast::t` is negative.
Here are my c2Ray and c2AABB:
```c++
c2AABB aabb;
aabb.min = c2V(80, 80);
aabb.max = c2V(120, 120);

c2Ray ray;
ray.p = c2V(100, 100);
ray.d = c2V(100, 100);
ray.t = 1;
```
I included a picture to illustrate the problem.
![screenshot from 2017-06-19 10-36-05](https://user-images.githubusercontent.com/17962301/27276309-1e3d1792-54db-11e7-89a5-baedb777a6b4.png)
PS: I hope it's ok if I keep opening issues for the bugs I find :)

**Comment by sro5h** [comment]
Ok, sorry didnt see your comment under the other issue, I will test it again.

**Comment by RandyGaul** [comment]
That's OK! Feel free to make as many of these issues as you would like. They are helpful.

Usually raycasts are not well-defined if the ray starts out inside of a shape. Rays are usually meant to try and find a time of impact, and are written to run very efficiently.

Games that use `c2RaytoAABB` generally make *a lot* of calls to `c2RaytoAABB`, so it is attempting do its work very quickly. Adding in additional code to place the time as 0 wouldn't really be very helpful in these cases.

My suggestion is before casting a ray, make sure there are no boxes on the ray's starting position. This can be done with a point to AABB collision check. If no boxes are in the way, then run the raycast function. I'm ganna close this issue out, but feel free to comment more if you have other questions or comments about ray to AABB checks.

**Comment by sro5h** [comment]
Ok sure, but I kind of get the feeling it's more me using the library in a wrong way then actual bugs

Didn't know casting from inside a Shape wasn't well defined. Intuitively I thought it should give me the Point on the Edge that actually intersects with the ray.

But I guess to do that there would be quite some additional effort that can be avoided this way :)

**Comment by RandyGaul** [comment]
You're right, it would be pretty intuitive to hit an edge when cast from the inside. And like you pointed out, lots of effort can be saved if we ignore such cases.

That's OK if these aren't actual bugs. The issues on github is also very useful for questions/suggestions/comments. Other people that come along and try out tinyc2 will have the same questions!

**Comment by sro5h** [comment]
I just noticed that `c2RaytoCircle` returns false if the ray starts in the circle because there you test for `t <= 0` (`if ( t >= 0 && t <= A.t )`). Wouldn't it be better if it was the same for `c2AABB` (and possibly the other shapes)?

**Comment by RandyGaul** [comment]
It's not quite that easy, since a negative time could also mean the ray started outside the circle but was pointing away from the sphere.

But that is a good point on consistency. Rays starting inside of shapes are currently not well defined in tinyc2, but maybe there's a good way to make them at least choose something consistent.

I'll think about that, but for now the best thing I can say is to treat rays starting inside of shapes as not well defined.
