### ISSUE TITLE
tinysound: Feedback and Feature Requests

### ISSUE THREAD

**Issue by ddengster** [RandyGaul/tinyheaders#33]
Ok, I've trying to integrate tinysound for some time, and just realized that it still lacks certain features I'd consider essential to a game.

1) Streaming 

The ogg/wav files are essentially loaded wholesale into memory as far as I can see. Load times thus suffer hard; and you can't always have all your sounds loaded at initialization time (I have ~200megs of sound, some of them are 5mb+). You can keep the file pointers (or oggstreams) in your tinysound structs, and stream the data using the mixer thread.

2) FreeSound() troubles

I'm using the lower level apis, and a separate thread for mixing, pools set to 0. When I call FreeSound() in the main loop upon a keypress (with the intention of playing another piece of ambient music), FreeSound() does not remove the playingsound pointer from the context's playing list. The examples don't test for such a case either - they all call FreeSound() at termination.

3) Music not playing on global focus (Windows)

Minor detail, but give an option to add DSBCAPS_GLOBALFOCUS to bufdesc.dwFlags for the secondary buffer on line 883, which allows music to be playing while the window is not focused.

All in all, tinysound isn't quite production ready yet. I can't quite consider it at version 1.0.

**Comment by RandyGaul** [comment]
Thanks for the post. Good suggestion on number 3!

For point 2: Use the high level API instead. The low level API is specifically made for people that want complete control over the memory usage, which implies that you'll have to take care of freeing memory when sounds aren't playing manually.

Also pretty sure if using the high level API, if a sound's audio is free'd the associated playing instances will deref the free'd memory and crash. I'll think about adding in a mechanism to catch that automatically. Pretty sure I can get in a feature for this within a week.

For point 1: OGG support done via stb_vorbis, which already has its own streaming API ([more info here](https://github.com/RandyGaul/tinyheaders/issues/12#issuecomment-284875473)). Hooking up some code into tinysound to handle streaming would be a great feature to add. I haven't added it yet as I personally haven't needed it. However, since you're now the second person to bring this point up it seems fairly important. I think a separate issue for this feature request sounds reasonable.

**Comment by RandyGaul** [comment]
Hmm. I'm not really sold on the idea of streaming in WAV files.

If a WAV file is causing a load time problem, then why not store it compressed as OGG, and load it in earlier? And at that point it can use the OGG streaming API from stb_vorbis.

In this way it seems like writing a streaming service for WAV files would be moot.

**Comment by RandyGaul** [comment]
Added an issue specifically for point 1 here: https://github.com/RandyGaul/tinyheaders/issues/34

**Comment by ddengster** [comment]
Some clarification: my game loads OGG files already(some of them 3-5mb a piece, total ~200 files), I preferably want to load music on demand and not at the initialization stage, because I can have quite a number of those and don't see the need to keep them in memory when I'm not using them. When I load OGG files during the game using tinysound, I get a frame spike of 0.5 to 1 second due to the loading; which is really bad for games. And on top of that I have other things to do during my game's initialization; this is not like graphics shaders where you can get away with loading 50 compiled shaders at the start of your game because they're so small in number and in memory for the game's lifetime.

Anyway, it's up to you, but for me this streaming feature is crucial for my game, at least for OGG files.

For others, here's some code for as to how oggstream&openal can be used to stream data. I suppose you could have something in tinysound that does what alBufferData does.

`#define AUDIO_SAMPLE_COUNT 1024 * 32
  ALshort data[AUDIO_SAMPLE_COUNT] = { 0 };

  uint samples_read_per_channel = stb_vorbis_get_samples_short_interleaved(stream->mOggStream,
    stream->mInfo.channels, data, AUDIO_SAMPLE_COUNT);
  uint samples_read = samples_read_per_channel * stream->mInfo.channels;
  stream->mRemainingUnreadSamples -= samples_read;
  
  if (stream->mLoop && stream->mOggStream->eof)
  {
    uint totalsamples = stb_vorbis_stream_length_in_samples(stream->mOggStream) * stream->mInfo.channels;
    ALshort* dataoffset = data + samples_read;
    while (samples_read < AUDIO_SAMPLE_COUNT)
    {
      //repeat fill the buffer so long as buffer has space
      stb_vorbis_seek_start(stream->mOggStream);
      
      uint samples_to_fill = AUDIO_SAMPLE_COUNT - samples_read;
      samples_read_per_channel = stb_vorbis_get_samples_short_interleaved(stream->mOggStream,
        stream->mInfo.channels, dataoffset, samples_to_fill);

      uint samples_readthisloop = samples_read_per_channel * stream->mInfo.channels;
      dataoffset += samples_readthisloop;
      samples_read += samples_readthisloop;

      stream->mRemainingUnreadSamples = totalsamples - samples_readthisloop;
    } 
    samples_read = AUDIO_SAMPLE_COUNT;
  }

  alBufferData(buffer, stream->mFormat, data, samples_read * sizeof(ALshort), stream->mInfo.sample_rate);
alSourceQueueBuffers(stream->mSource, 2, stream->mBuffers);`

**Comment by RandyGaul** [comment]
Closing this. Came up with a good way to support this in a new wrapper header for tinysound.

**Comment by hsdk123** [comment]
@RandyGaul Has this wrapper header been released?

**Comment by RandyGaul** [comment]
@hsdk123 Not yet! :)
