### ISSUE TITLE
Compilation of tiny2c.h fails under g++

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#35]
When compiling under linux g++ complains about memcpy not being declared:
```
In file included from main.cpp:4:0:
./tinyc2.h: In function ‘int c2Hull(c2v*, int)’:
./tinyc2.h:913:55: error: ‘memcpy’ was not declared in this scope
  memcpy( verts, hull_verts, sizeof( c2v ) * out_count );
```
Including `cstring` before `tiny2c.h` fixes the error.

Os: Ubuntu 16.04 LTS
Compiler: g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005

**Comment by RandyGaul** [comment]
Good catch! Fixed.
