### ISSUE TITLE
WIN64 in tinyfiles

### ISSUE THREAD

**Issue by coldragon** [RandyGaul/tinyheaders#39]
In TinyFiles I had to replace the line 54 with
`#if defined( _WIN32 ) || defined ( _WIN64 )`

for 64 bits compiling (on MVSC2015 and 2017 for sure).

You should add this on other header too.

It's not really important but it could be nice.

And thank's a lot for the work

**Comment by RandyGaul** [comment]
Sure thing, thanks for the comment. What were you using tinyfiles for if I may ask? :)

**Comment by coldragon** [comment]
For the little game on my GitHub, I need to list file in a map folder and
random select one to load the next level :)

**Comment by RandyGaul** [comment]
Just a bit curious how you managed to need `_WIN64`. I took a peek here: https://msdn.microsoft.com/en-us/library/b0084kay.aspx and noticed that `_WIN32` should always be defined for 32bit and 64bit builds. I'm under the impression `_WIN32` would work for *anything* compiled on Windows. Any ideas?

I'll close this for now, but feel free to open it if you would like me to take another look :)
