### ISSUE TITLE
dotc integration?

### ISSUE THREAD

**Issue by mreinstein** [RandyGaul/tinyheaders#41]
@RandyGaul I love this collection of small, useful, tight header files! I'm using tinyc2 in a game project right now. 

I'm wondering if you'd be open to a PR that integrates dotc: https://www.npmjs.com/package/dotc

The tl;dr is it's a preprocessor that copies the semantics of node's module lookup algorithm without modifying anything else about the c language.

What's really nice about this is you can expose only the things that you want to be available from your module and everything else stays private, (i.e., not in the global namespace.) 

If this is something you'd be interested in I'd be happy to send a PR (would basically look like this:)

```c
#ifdef DOTC
#export c2AABB
#export c2Ray
#export c2Circle
#export c2CircletoCircle
// etc....
#endif
```

**Comment by zao** [comment]
> without modifying anything else about the c language
Apart from the part where it compiles all your C as C++ as it depends on namespaces.

This is the wrong place for me to have this argument, but it annoys me when blatant untruths are propagated in an attempt to get adoption. C isn't a subset of C++, and most likely never will be.

**Comment by mreinstein** [comment]
> blatant untruths are propagated in an attempt to get adoption.

If you look at my background, you'll see I have a much stronger experience skill set with web stuff. I'm still new to c. I wasn't aware that dotc is turning all of the  source into c++.

I'm not telling an untruth or cheerleading anything purposefully to get adoption. It's not even my project. Coming from other languages that have proper modularity, this seems like a way to do sane c-style programming without polluting the global namespace.

**Comment by tombsar** [comment]
I agree with @zao's reaction in principle, but in this case the fact that dotc only supports C++ code is a moot point, because tinyheaders is already written to compile as either C or C++. It also looks as though all code changes are hidden behind `#ifdef DOTC`, so it won't break compatibility.

**Comment by mreinstein** [comment]
> I  agree with @zao's reaction in principle

I hope you don't also think that my ask for a PR is any attempt to intentionally lie or push an agenda. I really just proposed this as a way to enable what seems to be a neat way to namespace code.


> It also looks as though all code changes are hidden behind #ifdef DOTC,
> so it won't break compatibility.

Yeah. Obviously dotc is not a common/popular approach for most tinyheaders users. It's a tradeoff between polluting the code with a 40 line `#ifdef` and enabling people that would like to use this with dotc. Though this ifdef, could also double as a nice way to document the "public" API that `tiny2c` exposes. It's alluded to here: https://github.com/RandyGaul/tinyheaders/blob/master/tinyc2.h#L37-L56

**Comment by tombsar** [comment]
> I hope you don't also think that my ask for a PR is any attempt to intentionally lie or push an agenda.

Sorry, I didn't mean to accuse you of any of that. What I meant is that the dotc developers are either unaware that their project does not work with C (which doesn't instil confidence in the quality of their library), or that they are deliberately trying to mislead people by proclaiming C support all over their webpage. I suspect it's the former, since they do mention lower down on the page that "When somebody writes a namespace transform we can drop the forced c++ upgrade.".

**Comment by RandyGaul** [comment]
Hey there, thanks for the dotc idea. I hadn't ever heard of it before.

> node's module lookup algorithm

I actually have no idea what this is, but I did peek at the page. Require/export aren't apart of C, and unfortunately I would not want to clutter the header any more than needs be. The header portion of tinyc2 is the most important part of the entire file, so cluttering it should be avoided at all costs.

Anyways, thanks for the idea!

**Comment by zao** [comment]
Sorry for the kneejerk reaction, just a bit worn out by these kinds of requests across the projects I watch.

**Comment by mreinstein** [comment]
> Sorry

Thanks, I appreciate that! 👍 

> a bit worn out by these kinds of requests across the projects I watch

I hear ya. :)
