### ISSUE TITLE
TinySound thread issues..

### ISSUE THREAD

**Issue by AaronBalint** [RandyGaul/tinyheaders#42]
Awesome speed improvement on the pitch code!

I noticed a few issues:

You will need a tsLock() for tsSetPitch() OR read playing->pitch just once in tsMix()? In tsPlaySound() you will need an unlock:

```
if ( !playing )
{
	tsUnlock( ctx );
	return 0;
}
```

tsStopAllSounds() is not thread safe with tsMix()
A possible solution:

```
void tsStopAllSounds( tsContext* ctx )
{
        tsLock( ctx );
	tsPlayingSound* sound = ctx->playing;
	while ( sound )
	{
		// let tsMix() remove the sound
                sound->active = 0;
		sound = sound->next;
	}
        tsUnlock( ctx );
}
```

**Comment by RandyGaul** [comment]
Good catches! I'll get around to fixing these, but in the meantime I would accept a pull request if anyone sends one along :)

**Comment by RandyGaul** [comment]
Fixed.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/0ba9bc21292e5d0e6dfc3d154ba6f701cf1c28ef
