### ISSUE TITLE
tinysound: SDL1 Support - Looking for Pull Request

### ISSUE THREAD

**Issue by RobLoach** [RandyGaul/tinyheaders#48]
Any thoughts on having some SDL1.2 support?

**Comment by RandyGaul** [comment]
If a pull request came along I would consider it.

**Comment by RandyGaul** [comment]
Just tidying up a little bit -- don't think anyone is likely to contribute here since most people seem to use SDL2 nowadays. Feel free to open if anyone wants to work on this.
