### ISSUE TITLE
tinysound SDL: only right channel works

### ISSUE THREAD

**Issue by DeXP** [RandyGaul/tinyheaders#51]
Both Linux and Windows. I just compiled the demo with Visual Studio 2017 on Windows.
You can clearly hear it with headphones: left channel is always silent.

If change `wanted.channels` to 1, then both left and right have a sound, but 2 times slower than normal.

P.S. The demo can't be compiled in VS. You need to change 636 line from:
```
void* buf = data;
```
to:
```
char* buf = (char*)data;
```

**Comment by RandyGaul** [comment]
Was a one line fix.

	// Since the ctx->samples array is already in use as a ring buffer
	// reusing floatA to store output is a good way to temporarly store
	// the final samples. Then a single ring buffer push can be used
	// afterwards. Pretty hacky, but whatever :)
	__m128i* samples = (__m128i*)floatA;
	memset( samples, 0, sizeof( __m128i ) * wide_count ); // <<< Should not be here!!!
	for ( int i = 0; i < wide_count; ++i )
	{
		__m128i a = _mm_cvtps_epi32( floatA[ i ] );
		__m128i b = _mm_cvtps_epi32( floatB[ i ] );
		__m128i a0b0a1b1 = _mm_unpacklo_epi32( a, b );
		__m128i a2b2a3b3 = _mm_unpackhi_epi32( a, b );
		samples[ i ] = _mm_packs_epi32( a0b0a1b1, a2b2a3b3 );
	}
	tsPushBytes( ctx, samples, bytes_to_write );

It's a little tricky since I'm reusing the floatA buffer to store output. Muscle memory at the time wrote down a memset before writing the buffer (not really necessary, and caused a bug).

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/6d16c1ea7f8a173b54f233a690def8b4dfd28956

**Comment by DeXP** [comment]
Great thank you! It was too tricky for me to fix.
