### ISSUE TITLE
tinyc2: Inconsistent normal direction if using c2Collide

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#53]
If you use `c2Collide` to calculate the `c2Manifold` of a collision, the normal doesn't always point from shape A to B, if the type of A is different from the type of B. If both are of the same type the normal always points from A to B. This happens because the arguments of `c2XtoX` functions for different shape types have a fixed order.
E.g. Shape A is a `c2Circle` and B is a `c2AABB`.
```c
// If passed in this order the normal will point from A -> B.
c2Collide(&A, NULL, C2_CIRCLE, &B, NULL, C2_AABB, &manifold);
```
Now switch the shapes, A now is a `c2AABB` and B a `c2Circle`
```c
// Now c2Collide will call c2CircletoAABBManifold(*B, *A, manifold)
// If passed in this order the normal will point from B -> A.
c2Collide(&A, NULL, C2_AABB, &B, NULL, C2_CIRCLE, &manifold);
```

A simple solution would be: For each call in `c2Collide` where A and B are switched (e.g. `c2XtoX(*B, *A, &m)`) the normal needs to be inverted.

**Comment by RandyGaul** [comment]
Oh yes, you're totally right. This is a minor oversight. For these cases the normal would need to be flipped. Like you pointed in in any case where B and A are swapped in a function call, the returned normal should be flipped.

**Comment by sro5h** [comment]
I can make a pullrequest, i already fix it while testing, e.g.:
```c
case C2_CIRCLE: c2CircletoAABBmanifold( *(c2Circle*)B, *(c2AABB*)A, m ); return c2InvertManifold(m);
```

**Comment by RandyGaul** [comment]
Bumped version number and credited you! Thanks for the great work in improving the consistency of all the manifold functions :)
