### ISSUE TITLE
Implement tpCompact in tinypath.h

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/tinyheaders#64]
`tpCompact` would be a useful function to have. It would shorten a path to a specified character limit by placing an ellipses. Would work similar to [PathCompactPathEx](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773578(v=vs.85).aspx).

    int tpCompact( const char* path, char* out );

See: https://github.com/RandyGaul/tinyheaders/blob/master/tinypath.h#L68

**Comment by sro5h** [comment]
I have got a working version that just uses standard library functions. But i just saw `tpPop` and i think i could make use of it and simplify my `tpCompact`. Just wanted to let you know that i am trying to implement it :)

**Comment by RandyGaul** [comment]
Very cool! I’m anxious to see :)

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/pull/68
