### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by irlanrobson** [RandyGaul/tinyheaders#7]
Randy, to correctly convert from nanoseconds to seconds on Linux change this line

float elapsed = (float)((double)(now.tv_nsec - prev.tv_nsec) * 1e9);

to

float elapsed = (float)((double)(now.tv_nsec - prev.tv_nsec) * 1e-9);

**Comment by RandyGaul** [comment]
Thank you very much for the catch Irlan! Fixing right now.
