### ISSUE TITLE
tinymath2d: C++ wrapper for tinyc2 functions

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#71]
Considering the addition of `tinymath2d` i think it would be nice to have a C++ wrapper for `tinyc2`. I'm thinking of a base class `c2Shape` that holds the position information so the user could manipulate the position of a shape without knowing what type it is (which is something i am missing from `tinyc2`). Kind of like that:
```c++
namespace c2 {

struct Shape
{
        c2v position;
};

struct Aabb : public Shape
{
        float w;
        float h;
};

struct Circle : public Shape
{
        float r;
};

.
.
.

void collide(const Shape& A, const Shape& B, c2Manifold* m)
{
        // Calculate the manifold
}

}
```
One would need to cast the `Shape` to calculate the manifold then (either using the c API from `tinyc2` or `tinymath2d` if possible). It would be nicer though to avoid the cast, but i can't think of way to do this right now.  
Anyway just wanted to hear your opinion on that

**Comment by RandyGaul** [comment]
Most of the tinyheaders are intended to be wrapped by users and then placed into their code bases. For example, I'm thinking of making a tinysound wrapper header sometime soon to manage lifetime of playing sounds. It could be nice to host a collection of wrapper headers, maybe in a separate repository called `tinywrappers` or something :)

Anyways, I think it's a fine idea if someone wants to wrap tinyc2. To modify the position of a shape I would definitely use a `Mul` function in C++ with function overloading:

```cpp
using Transform = c2x;
using Circle = c2Circle;
using Capsule = c2Capsule;
using AABB = c2AABB;

Circle Mul(Transform tx, Circle a);
Circle MulT(Transform tx, Circle a);
Capsule Mul(Transform tx, Capsule a);
Capsule MulT(Transform tx, Capsule a);
AABB Mul(Transform tx, AABB a);
AABB MulT(Transform tx, AABB a);
```

It is useful to be able to transform a shape in a generic way with `Mul` and `MulT` functions. `Mul` stands for "multiply" and `MulT` stands for "multiply transpose". Implementing the functions can be a little tricky at first, but it's not too hard. The tricky part is that not all shapes can be rotated, but at least they can all be translated. For example the `AABB` cannot be rotated, so `Mul` would simply add position to the  `min` and `max` data members.

**Comment by sro5h** [comment]
Sounds like an interesting idea to add a `tinywrappers` repo, but right now it would be pretty empty i guess :smile: 
What are your plans with tinymath2d then? Right now the API seems to be pretty similar to tinyc2, why not take advantage of inheritence and polymorphism?

**Comment by RandyGaul** [comment]
Plan for tinymath2d is to add in raycast functions and `mul` functions over time. It's intended to be used as a general purpose vector math and shape library, but without all of the beefy collision detection functions.

tinyc2 is not a useful vector math library because it's written in plain C, so there's no nice function overloading features. Instead, it is only supporting the big beefy collision and raycast functions. It's in plain C so more people can use it without requiring C++.

The example I gave you with overloaded `mul` functions actually is polymorphism. Polymorphism in a nutshell means "same API with different data gives different results".

What kind of polymorphism did you have in mind? What problems would you be solving with polymorphism and inheritance?

**Comment by sro5h** [comment]
Ok i thought you were planning to add them aswell :)

Sure, i wasn't questioning the purpose of tinyc2. I thought you wanted tinymath2d to be a c++ version of tinyc2


Well i thought having a base class would make it easy to manipulate common properties (position, rotation) through and keep shapes in one place. But of course the first one can be solved by overloaded functions as you said.

**Comment by RandyGaul** [comment]
Oh! yeah tinymath2d is just a vector math library :)

**Comment by sro5h** [comment]
Ok i'll close this then :)

**Comment by RandyGaul** [comment]
OK no problem! Feel free to open more issues if you had other questions/comments :D

**Comment by sro5h** [comment]
Well really the only problem i have right now is that i would like to store all shapes in one list. I just want to manipulate the position of each shape and check whether it collides with some other shape, but i don't really care about what kind of shape it is after creating it. How would you go about this?

**Comment by RandyGaul** [comment]
I would do this:

```cpp
union ShapeHolder
{
    c2Circle circle;
    c2Capsule capsule;
    c2AABB aabb;
};

enum ShapeType
{
    eCircle,
    eCapsule,
    eAABB,
};

struct Shape
{
    ShapeType type;
    ShapeHolder shape;

    void Translate(v2 pos)
    {
        switch (type)
        {
        case eCircle:
            shape.circle.p += pos;
            break;

        // ...
        }
    }
};
```

**Comment by sro5h** [comment]
That's way nicer then my initial thoughts, thanks :)

**Comment by RandyGaul** [comment]
No problem :)
