### ISSUE TITLE
tinyutf.h, declare tuWiden/tuShorten and break from while loop if encountering a null terminator

### ISSUE THREAD

**Issue by ddengster** [RandyGaul/tinyheaders#74]
As per title, I'm using tuWiden/tuShorten, but I'm finding that they carry on iterating even after a null terminator. This shouldn't be happening, no?

**Comment by RandyGaul** [comment]
They take a length parameter, is in length of the input buffer or length of the output buffer. They are dead simple wrappers over decode/encode. Feel free to make your own wrapper function that does exactly what you want if you don't really like the ones that come with the header.

Here's an example that works without buffer lengths (didn't test the code, but hopefully it works the way you expected):

	void Widen(const char* in, whcar_t* out)
	{
		char c;
		int cp;
		while (c = *in)
		{
			in = tuDecode8(in, &cp);
			out = tuEncode(out, cp);
		}
	}

**Comment by RandyGaul** [comment]
OK I'll make these functions and push them out. Thanks for asking @ddengster ! Closing for now, comment away if you wanted to chat more.
