### ISSUE TITLE
Errors out on wave files with fact chunk

### ISSUE THREAD

**Issue by kavika13** [RandyGaul/tinyheaders#79]
Line 566 assumes the first chunk will be a `data` chunk, but this is not always the case.

In my case, I have a wav file with a `fact` chunk, and the load routine errors out.

**Comment by RandyGaul** [comment]
Could you please share the wav file to allow me to build a repro? Either that, or submit a pull request with the fix? It looks like `tsNext` can be used in a loop until the `data` chunk is found.

**Comment by kavika13** [comment]
[Select.zip](https://github.com/RandyGaul/tinyheaders/files/1734201/Select.zip)

BTW, I stuck this code in, and "it worked for me":
```
	TS_CHECK( fmt.nBlockAlign == fmt.nChannels * 2, "implementation error" );

	data = tsNext( data );
	if (tsFourCC("fact", data)) {  // New check here...
		data = tsNext(data);
	}

	TS_CHECK( tsFourCC( "data", data ), "data chunk not found." );
```

Sorry for no PR (yet), hopefully this helps anyway!

**Comment by RandyGaul** [comment]
That's OK. I have time to take a look today :)

Thanks!

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/3f4476e47484ed18cfdeee54956ad512ea54ef88
