### ISSUE TITLE
tsStopAllSounds() does not mark sounds as inactive

### ISSUE THREAD

**Issue by AaronBalint** [RandyGaul/tinyheaders#8]
In tsStopAllSounds() need to add
sound->active = 0;
or call tsStopSound();

**Comment by RandyGaul** [comment]
Hi thanks for the suggestion. Just to double check; this is to solve the case of using low-level API, where the sound->active flag is still 1 even after being removed from the playing pool?

**Comment by AaronBalint** [comment]
For High Level API:
tsPlayingSound* sound = tsPlaySound( ctx, def );

and from the documentation:
// All of the functions in this next section should only be called if tsIsActive
// returns true.

I was tempted to use the tsPlayingSound pointer for later manipulation (change volume, pitch etc).   However since the pointer can be re-allocated from the end of one sound to the start of another by the context; this could be an inappropriate use of the High Level API ?

**Comment by RandyGaul** [comment]
That makes perfect sense, thanks for explaining that!

**Comment by RandyGaul** [comment]
Fixed
