### ISSUE TITLE
Calling tsFree on a stopped sound triggers race condition when using mix thread

### ISSUE THREAD

**Issue by kavika13** [RandyGaul/tinyheaders#82]
Depending on when exactly the mix thread is executing, it can hit an assert on the presence of channels on a stopped and freed sound. It doesn't seem to use this channel value in this case, since it jumps to the `remove:` label first.

This might be fixed by making tsMix check `playing->active` before trying to pull channel data and doing assertions.

**Comment by RandyGaul** [comment]
This is an on-going issue with tinysound's "high level api". There is a steep slippery slope when dealing with freeing audio while also playing sounds. More book-keeping is needed, but I really don't want to start bloating tinysound with more features.

I'm actually considering removing the "high level api" from tinysound entirely. Then a new wrapper header, probably called `tinysound_wrapper.h`, will be created. The wrapper would provide some higher level features, like instance pooling, notification callbacks when sounds stop playing, and a similar mechanism for safely free'ing audio resources.

For now, if you want fine-grained control over freeing your audio source, you should not use the high level api, and instead explicitly manage your own memory and playing instances with the low level api. You will, at least for now, have to poll the `active` member of the playing sound instance. Ideally a callback could be used here so polling is not necessary, but this would be better suited for a wrapper.

Closing this for now, but feel free to re-open or comment if you like.

**Comment by kavika13** [comment]
In this case, I was able to move this code to the top of the loop, and stopped seeing the assertion. This didn't require any extra bookkeeping to make the code more safe:

```
while ( *ptr )
{
	tsPlayingSound* playing = *ptr;

	// moved this code up from below...
	// immediately remove any inactive elements
	if ( !playing->active || !ctx->running )
		goto remove;
```

I looked at the call to stop both stop and free, and I think it's currently safe to do this. However, I'd of course feel more comfortable with that if the calls were audited and intentionally made to be safe in that context :) I'm about to go on vacation, or I'd actually dive in, figure out if this is actually safe, and create a pull request.

As for the need for this - I honestly should be storing or pooling sounds, instead of constantly unloading and reloading them, but I wanted to file the bugs I ran into. I also didn't realize that there were callbacks for when sounds stopped. I think that could help a lot for cleanup code.

I think it is possible a small patch could be made to fix these cases without adding any extra storage or having to refactor significantly.

**Comment by kavika13** [comment]
Whoops, didn't realize I was editing and had already posted it :) I should probably wake up before doing software stuff.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/9963ebcefde4b5184fede96c474050614b8fd873
