### ISSUE TITLE
Sounds with lower sample rate get time stretched

### ISSUE THREAD

**Issue by kavika13** [RandyGaul/tinyheaders#83]
I had some sound effects from an old game that were 8 bit and were way less than 44.1khz. An assertion was thrown for those files since 8 bit support hasn't been implemented yet. I imagine sounds this low quality aren't common these days, so this part seems lower priority.

However, I tried upgrading them to 16 bit. They did not assert on load. Instead, they played back something like 2x faster and higher pitched than they should. It took me a while to realize Audacity and foobar2000 weren't buggy, and neither of them were upping the file to 44.1hz while "exporting to 16 bit audio".

Here's the 16 bit version, after my less successful conversion. This is the one that plays time stretched, and does not assert on load:
[Fire-16bit-22.05khz.zip](https://github.com/RandyGaul/tinyheaders/files/1734210/Fire-16bit-22.05khz.zip)

Here's the original 8 bit version, in case the solution to the above ends up being resampling, rather than another assertion, and anyone feels like tackling this at the same time:
[Fire-8bit-22.05khz.zip](https://github.com/RandyGaul/tinyheaders/files/1734209/Fire-8bit-22.05khz.zip)

**Comment by RandyGaul** [comment]
Interesting. In theory you should be able to pad the old audio with extra empty samples, evenly spread through the audio. Then interpolate between each old sample. I imagine a spline could be used to help smooth out the interpolation.

I've never written code to do this before, and never have messed much with Audacity or other programs -- so I can't really help here!

**Comment by kavika13** [comment]
I solved this on my end by upsampling both the bit rate and the sample frequency in a third party program. I am fine with this since I was already doing a huge overhaul by converting midis to oggs with a really nice sound font.

I think the library should probably assert if it can detect it will fail to play back correctly, at the minimum. This is the same as the 8 bit vs 16 bit sample thing. The uber-luxury version would do something more like stb_image, of course.

**Comment by RandyGaul** [comment]
> I think the library should probably assert if it can detect it will fail to play back correctly, at the minimum. 

What exactly might be detected? I'm not quite understanding this part.

**Comment by kavika13** [comment]
I meant asserting that it matches the target format. But I guess `tsReadMemWAV` doesn't have any dependencies on the target context or target format at this time.

I had assumed it did, since that's what stb_image does in `stbi_load`. It makes sense that one of these this dependencies wasn't previously taken, since `tsReadMemWAV` doesn't currently do conversions.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/blob/master/tinysound.h#L565

Here is a check for the correct bits per sample. Do you mean add in another check like this, to look for a matching sample rate to the context mix rate?

**Comment by kavika13** [comment]
Right I meant either add an assert (which would require passing extra parameters so it can determine the target rate, I think?), or not add assert and do a sample conversion instead.

As for which one - I'm sort of leaving that one up to you :) I don't entirely know the goals for the library (sound loader? mini-SDL? fast path to a working implementation if you're willing to forego anything but the best formats?).

Triggering an assertion might prevent some hair-pulling, at the least.

**Comment by RandyGaul** [comment]
Ah thanks for that. I'll make a quick additional assert. I think an extra parameter like you mentioned is a good idea.

**Comment by RandyGaul** [comment]
https://github.com/RandyGaul/tinyheaders/commit/ca58436b4688bc83add54a52b3f995fbca7cbf6b

Decided to put sample rate into the loaded sound itself. Users can do whatever validation checks or conversions they like, once they notice a source file has an unexpected sample rate.

Closing for now, but feel free to re-open or comment here.
