### ISSUE TITLE
tinyc2.h bug in circle to aabb manifold

### ISSUE THREAD

**Issue by RandyGaul** [RandyGaul/tinyheaders#85]
Realized some bugs that have persisted for around 8 years! Yes, some code in tinyc2.h is almost a decade old at this point :)

c2CircleToAABBManifold has some bugs in the deep penetration case. They are fairly easy to fix, but it did take a number of hours to thoroughly debug the issue.

I have fixes in a recent game jam I took part in -- but I need to dedicate some time to pull them into tinyc2.h and write a thorough test to ensure correctness.

I'm especially busy with work for the next couple weeks, but should have some time later this month to knock this task out. In the meantime if anyone is reading this and curious, it might be fun to try and spot the bug yourself!

**Comment by RandyGaul** [comment]
So the bug is here: https://github.com/RandyGaul/tinyheaders/blob/master/tinyc2.h#L1224-L1264 Basically this entire portion of code is incorrect. It should instead look more like this working solution here: https://github.com/Maximiliankk/GameJam2/blob/master/Assets/tail_chain.cs#L102-L129

**Comment by RandyGaul** [comment]
![c2circletomanifold_buf](https://user-images.githubusercontent.com/1919825/37880907-8bf0d4be-3044-11e8-814d-c2c4a9a173c6.gif)

The manifold is incorrect for AABBs that are not squares. In this gif, the manifold's resolution vector should *always* be pointing straight upwards.

**Comment by RandyGaul** [comment]
![c2circletomanifold_buf_fixed](https://user-images.githubusercontent.com/1919825/37881036-861c578c-3046-11e8-9390-1ab4343367a6.gif)

Fixed! https://github.com/RandyGaul/tinyheaders/commit/970b506e085de018b8fd284a1336b4bda7001d9c

**Comment by RicoP** [comment]
thanks for the work!
