### ISSUE TITLE
tinytiled: Example to index each vert of a polygon

### ISSUE THREAD

**Issue by selimanac** [RandyGaul/tinyheaders#88]
Since vert_count return total number of polygons, increasing i += 2 cause the loop end earlier.  This is not a big deal of course but it should be something like this:

```cpp
float x, y;
int a = 0;
for (int i = 0; i < o->vert_count; i++)
{		
 x = o->vertices[a];
 y = o->vertices[a + 1];
 printf("%f, %f\n", x, y);		
 a += 2;	
}
```

https://github.com/RandyGaul/tinyheaders/blob/769766b8ce833712377c639fc9005ce6a72ce0b7/tinytiled.h#L168

**Comment by RandyGaul** [comment]
Good catch! Thank you very much :)

https://github.com/RandyGaul/tinyheaders/commit/6075d2255c017a68b6665698af3318c79af12019
