### ISSUE TITLE
tinysound: Standard free should be used in tsReadMemOGG

### ISSUE THREAD

**Issue by empyreanx** [RandyGaul/tinyheaders#90]
STB Vorbis allocates memory using malloc, so free should be used in tsReadMemOGG to deallocate "samples" instead of using TS_FREE. I found this problem by replacing the standard allocator with rpmalloc.

**Comment by RandyGaul** [comment]
Good catch, thanks! Will fix shortly.

**Comment by RandyGaul** [comment]
Should be fixed: https://github.com/RandyGaul/tinyheaders/commit/f962d488acc89920ec504b598f5a33c67cdf7689
