### ISSUE TITLE
Possible issue with poly collisions 

### ISSUE THREAD

**Issue by DJLink** [RandyGaul/tinyheaders#92]
Hello,
Sory if this is a silly question, are poly collisions only supposed to return positive manifold count when intersecting or just touching?
The reason I ask is because I ran into an issue where with AABB it detects when touching and not with poly with exact same values, is this the expected behavior? Apologies if my code is wrong and is just a mistake I made.

With c2AABBtoAABBManifold
![aabb_collision](https://user-images.githubusercontent.com/423769/38871746-98f3b318-4249-11e8-81b8-f5e9ba994ee9.PNG)
With c2PolytoPolyManifold
![polygon_collision](https://user-images.githubusercontent.com/423769/38871749-991da4c0-4249-11e8-9005-f7d158c43257.PNG)

I wrote a quick test function that can easly copy-pasted into the tinyc2 sample.

```
void TestManifold( )
{
	bool draw_aabb = false;
	c2AABB bb;
	bb.min = c2V( -150.0f, 20.0f );
	bb.max = c2V( -60.0f, 140.0f );
	
	// bb things
	c2AABB ba;
	ba.min = c2V( -50.0f, -200.0f );
	ba.max = c2V( 50.0f, -100.0f );

	bb.min = c2V( -10.0f, -225.0f );
	bb.max = c2V( 49.0f, -200.0f );

	if (draw_aabb)
	{
		DrawBB(ba, bb);
	}
	else
	{
	       //Dirty conversion for poly just for tests
		c2Poly p1;
		c2BBVerts(p1.verts, &ba);
		p1.count = 4;
		c2Norms(p1.verts, p1.norms, 4);

		c2Poly p2;
		c2BBVerts(p2.verts, &bb);
		p2.count = 4;
		c2Norms(p2.verts, p2.norms, 4);

		c2x cx = c2xIdentity();
		tgLineColor(ctx, 1.0f, 1.0f, 1.0f);
		DrawPoly2(&p1, cx);
		DrawPoly2(&p2, cx);

		c2Manifold m;
		m.count = 0;
		c2PolytoPolyManifold(&p1, nullptr, &p2, nullptr, &m);
		DrawManifold(m);
	}
}
```

**Comment by DJLink** [comment]
Follow up, found another thing, if I align both boxes to right side, even when intersecting it doesn't detect any collision with polygons, only with AABB. I'm guessing I'm doing something wrong here, can't figure out what.

Poly aligned to right (A.x = 50, B.x = 50) doesn't detect colision
![polygon_collision2](https://user-images.githubusercontent.com/423769/38872727-dda1fc20-424b-11e8-975e-4dba94f09474.PNG)

Poly not aligned (A.x = 50, B.x = 49), detects colision
![polygon_collision_not_aligned](https://user-images.githubusercontent.com/423769/38872766-f2d63750-424b-11e8-962d-a242259d336b.PNG)

**Comment by RandyGaul** [comment]
For polygons "just touching" is not a very well defined criteria, unfortunately. It becomes really difficult to define these cases consistently. Since different functions use different algorithms, and since points are represented in floating point format, there is no way to consistently support a "touching" case. Instead, tinyc2 only focuses on intersecting and not-intersecting. This should not be a problem for games.

Your second post looks like a bug. Could you please paste the code for setting up a test case? I can take a look one of these evenings :)

**Comment by DJLink** [comment]
Hello Randy, thank you for such a quick reply
Here's a bit of code that you can use to reproduce it, hope this isn't just me using it wrong

You can use the bool flag to quickly see between with aabb and poly collisions.
Changing bb.max = c2V( 50.0f, -180.0f ) to c2v(49.0f, -180.0f)  will make it work as boxes are no longer aligned in one side, from what I found as long as it's aligned in left or right it will fail.
Thanks for helping with this. 

```
void TestManifold( )
{
	bool draw_aabb = false;
	
	c2AABB ba;
	ba.min = c2V( -50.0f, -200.0f );
	ba.max = c2V( 50.0f, -100.0f );

	c2AABB bb;
	bb.min = c2V( -10.0f, -225.0f );
	bb.max = c2V( 50.0f, -180.0f ); //<= if using 49 instead of 50 collision will work
	
	if (draw_aabb)
	{
		DrawBB(ba, bb);
	}
	else
	{
		//Dirty conversion for poly just for tests
		c2Poly p1;
		c2BBVerts(p1.verts, &ba);
		p1.count = 4;
		c2Norms(p1.verts, p1.norms, 4);

		c2Poly p2;
		c2BBVerts(p2.verts, &bb);
		p2.count = 4;
		c2Norms(p2.verts, p2.norms, 4);

		c2x cx = c2xIdentity();
		tgLineColor(ctx, 1.0f, 1.0f, 1.0f);
		DrawPoly2(&p1, cx);
		DrawPoly2(&p2, cx);

		c2Manifold m;
		m.count = 0;
		c2PolytoPolyManifold(&p1, nullptr, &p2, nullptr, &m);
		DrawManifold(m);
	}
}
```

**Comment by RandyGaul** [comment]
Fixed! Here was the bug: https://github.com/RandyGaul/tinyheaders/commit/ce2423727e85bd3741df738a4288c45b8ac42838#diff-280a7b4eb73256a7282ab8165d4fc89bL1448

This needed to `<=`. That line is attempting to do a sign test. If a perfect zero is passed in, the test fails. Thanks for reporting the bug! Let me know if you still have any other problems. Closing for now, but feel free to comment or re-open if needed.
