### ISSUE TITLE
Inconsistent naming of the normal in c2Manifold and c2Raycast

### ISSUE THREAD

**Issue by sro5h** [RandyGaul/tinyheaders#94]
I just stumbled upon the fact that the naming of `c2Manifold::normal` and `c2Raycast::n` is incosistent. I think it is confusing and should be either n or normal.

**Comment by RandyGaul** [comment]
Good idea. I'll stick with n. https://github.com/RandyGaul/tinyheaders/commit/f4ba3bbfe327aaae724681aec0f83677c6eea438
