### ISSUE TITLE
tinytiles layers are added in reverse order

### ISSUE THREAD

**Issue by ZenToad** [RandyGaul/tinyheaders#98]
The code only keeps the pointer to the front of the layer linked list, so each new layer is added to the front.  But the layers are listed in render order, so I have to read all the layers and reverse them to render.

**Comment by ZenToad** [comment]
Let me think about it.  It seemed like there aren't going to be too may layers, and searching for the end of the list wouldn't be too much extra code, but I wasn't sure how efficient you want this stuff.

Let me finish my renderer, and then I can update the code and go from there.

**Comment by RandyGaul** [comment]
So far I’m thinking of just using a stack, a stack allocated stack of pointers. Then have a code path just in case the stack limit is reached.

This is the simplest robust solution I can think of.

**Comment by ZenToad** [comment]
I would just do somthing like, this, but I try and do everything to simple it hurts.
if layer is null, layer = ptr
else
while(layer->next) layer = layer->next
layer->next = ptr

**Comment by RandyGaul** [comment]
I didn't realize could reverse list without any auxiliary memory. Does that actually work?

**Comment by RandyGaul** [comment]
Fixed https://github.com/RandyGaul/tinyheaders/commit/077e65096f24e7ef7921e1b50a1485584bcec733
