### ISSUE TITLE
Crash when loading bwf wave

### ISSUE THREAD

**Issue by r-lyeh** [RandyGaul/tinyheaders#99]
Please check attached wave file.

I think it crashes because of an unpexected 'bext' chunk, but have in mind that wav files may include many other additional chunks as well. Check ref: https://en.wikipedia.org/wiki/Broadcast_Wave_Format

For now, I think Tinysound should just skip all additional chunks, I guess :)

[demo.zip](https://github.com/RandyGaul/tinyheaders/files/1974110/demo.zip)

**Comment by RandyGaul** [comment]
Thanks! Yep, I was afraid of this. Thanks for submitting some more test WAV files :)

**Comment by RandyGaul** [comment]
Fixed https://github.com/RandyGaul/tinyheaders/commit/0fba5df9fd809d75165c20b65f87bf56e8bda417
